version: "3.5"
services:
  db:
    container_name: mysql_coder
    image: mysql:8.0
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: billing
      MYSQL_USER: coder
      MYSQL_PASSWORD: coder
    volumes:
      - mysql-billing-db:/var/lib/mysql
volumes:
  mysql-billing-db: